/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type ZoneReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "zone"
}

export type Location = {
  _type: "location"
  zone?: ZoneReference
  address?: string
  showAddress?: boolean
  geopoint?: Geopoint
}

export type Price = {
  _type: "price"
  amount?: number
  currency?: "USD" | "ARS"
}

export type Operation = {
  _type: "operation"
  type?: "sale" | "rent" | "temporaryRent"
  price?: Price
}

export type PropertyReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "property"
}

export type Lead = {
  _id: string
  _type: "lead"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  phone?: string
  email?: string
  message?: string
  property?: PropertyReference
  source?: "form" | "whatsapp"
  status?: "new" | "contacted" | "closed"
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type Agency = {
  _id: string
  _type: "agency"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  phone?: string
  whatsapp?: string
  email?: string
  address?: string
  socials?: {
    instagram?: string
    facebook?: string
  }
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Zone = {
  _id: string
  _type: "zone"
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  city?: string
  province?: string
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type Property = {
  _id: string
  _type: "property"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  code?: string
  propertyType?:
    | "house"
    | "apartment"
    | "ph"
    | "land"
    | "commercial"
    | "office"
    | "warehouse"
    | "garage"
    | "farm"
  operations?: Array<
    {
      _key: string
    } & Operation
  >
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  location?: Location
  bedrooms?: number
  bathrooms?: number
  rooms?: number
  coveredArea?: number
  totalArea?: number
  parkingSpaces?: number
  age?: number
  condition?: "brandNew" | "used" | "preConstruction"
  maintenanceFee?: Price
  amenities?: Array<string>
  mainImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
  }
  gallery?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    _key: string
  }>
  status?: "available" | "reserved" | "sold" | "rented"
  featured?: boolean
  instagramUrl?: string
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type AllSanitySchemaTypes =
  | ZoneReference
  | Location
  | Price
  | Operation
  | PropertyReference
  | Lead
  | SanityImageAssetReference
  | Agency
  | SanityImageCrop
  | SanityImageHotspot
  | Zone
  | Slug
  | Property
  | Geopoint
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset

// Source: src/features/properties/queries/build-properties-query.ts
// Variable: propertiesQuery
// Query: *[_type == "property"    && status == "available"    && (!defined($types) || propertyType in $types)    && (!defined($zones) || location.zone->slug.current in $zones)    && (!defined($rooms) || rooms >= $rooms)    && (!defined($bathrooms) || bathrooms >= $bathrooms)    && (!defined($areaMin) || coveredArea >= $areaMin)    && (!defined($areaMax) || coveredArea <= $areaMax)    && (!defined($parking) || parkingSpaces >= $parking)    && (!defined($conditions) || condition in $conditions)    && (!defined($amenities) || count(amenities[@ in $amenities]) == count($amenities))    && (!defined($q) || title match $q || code match $q || (location.showAddress == true && location.address match $q))  ] | order(_createdAt desc) {    _id,    title,    "slug": slug.current,    rooms,    bathrooms,    coveredArea,    "zone": location.zone->name,    operations[]{ type, price },    mainImage {      ...,      "lqip": asset->metadata.lqip    }  }
export type PropertiesQueryResult = Array<{
  _id: string
  title: string | null
  slug: string | null
  rooms: number | null
  bathrooms: number | null
  coveredArea: number | null
  zone: string | null
  operations: Array<{
    type: "rent" | "sale" | "temporaryRent" | null
    price: Price | null
  }> | null
  mainImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: "image"
    lqip: string | null
  } | null
}>

// Source: src/features/search/queries/get-zones.ts
// Variable: zonesQuery
// Query: *[_type == "zone"] | order(name asc) {    "slug": slug.current,    name  }
export type ZonesQueryResult = Array<{
  slug: string | null
  name: string | null
}>
